name: Node.js CI

on:
  push:
    branches: [ "Taxi-app-design" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install -y nodejs npm
    - run: |
        if [ -f "package-lock.json" ]; then
          echo "Deleting package-lock.json file"
          rm -r package-lock.json
        else
          echo "package-lock.json file not found"
        fi
    - run: npm i -f
    - run: echo "${{secrets.PROD_ENV}}" >.env
    - run: npm run build
    - run: |
        if [ -d "node_modules" ]; then
          echo "Deleting node_modules directory"
          rm -r node_modules
        else
          echo "node_modules directory not found"
        fi
